config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    resources :comments
  end
  devise_for :users
   root to: 'projects#index'
   resources :projects
  
  authenticated :user do
    root 'projects#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
  has_one_attached :image
  
  class << self
    def replies(parent_comment_id,page)
      child_comments_ids = all_children_recursion(parent_comment_id)
      child_comments_ids << parent_comment_id
      where("parent_comment_id IN (?)",child_comments_ids).order("created_at ASC").paginate(page: page, per_page: 5)
    end
  
    def all_children_recursion(id)
      where(parent_comment_id: id).flat_map do |child_cat|
        all_children_recursion(child_cat.id) << child_cat.id
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
      has_and_belongs_to_many :users
      has_many :tasks
      has_many :comments, :through => :tasks
      validates :name,:description, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    enum status: [ :inprogress,:hold, :complete ]
    validates :name,:user_id,:project_id, presence: true
    validate :end_date_is_after_start_date

    belongs_to :project
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :parent_replies, -> (parent_comment_id) { where(parent_comment_id: nil) }, class_name: "Comment",foreign_key: "task_id"
  
 
  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?
  
    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date") 
    end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :projects
  has_many :tasks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery prepend: true
    
    def after_sign_in_path_for(resource)
	    stored_location_for(resource) || projects_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_task
  
  def index
    if params[:parent_comment_id].present?
      @comments = Comment.replies(params[:parent_comment_id], params[:parent_page])
      params[:parent_page] = @comments.next_page
    else
      @comments = @task.parent_replies.paginate(page: params[:page], per_page: 5)
    end
  end
  
  def new
    @parent_comment_id = params[:parent_comment_id]
  end
  
  def create
    @comment = Comment.create(comment_params)
    redirect_to task_path(@task)
  end
  
  private
  
  def load_task
    @task = Task.find(params[:task_id])
  end
  
  def comment_params
    params.require(:comment).permit(:content,:user_id,:task_id,:parent_comment_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_ids = params[:project][:user_ids]
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
    @project.user_ids = params[:project][:user_ids]
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comments = @task.parent_replies.paginate(page: params[:page], per_page: 5)
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :name, :description, :status, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<% is_parent_comment = comment.parent_comment_id.blank? %>
<div data-id="comment-wrapper-<%= comment.id %>">
  <div class="row align-items-center <%= is_parent_comment ? '' : 'offset-md-1' %>">
    <div class="col-4">
      <%#= image_tag comment.user.avatar_image,size: User::SIZE[:small],class: "mr-2" %>
      <%= comment.user.email %>
    </div>
    <div class="col-3 text-right">
      <%= link_to "Reply",new_task_comment_path(@task.id,parent_comment_id: comment.id), data: { id: "reply-box", "db-id": comment.id },remote: true %>
    </div>
    <div class="col-5 text-left"> Posted <%= time_ago_in_words(comment.created_at) %> ago.</div>
  </div>
  <div data-id="comment-form" data-comment-id="<%= comment.id %>" class="<%= is_parent_comment ? '' : 'offset-md-1' %>">
    <div class="col-10"><%= sanitize comment.content %></div>
    <div data-id="render-form"></div>
  </div>
  <% unless local_assigns.has_key?(:recursive) %>
    <% comment_replies = Comment.replies(comment.id,params[:parent_page] || 1) %>
    <div data-id="link-wrap-<%= comment.id %>">
      <%= render partial: 'comments/comment', collection: comment_replies,locals: { recursive: true} %>   
    </div>
    <% if comment_replies.present? && comment_replies.next_page %>
      <div class="<%= is_parent_comment ? '' : 'offset-md-1' %>" data-id="comment-more-<%= comment.id %>">
        <%= link_to 'Load More', task_comments_path(@task.id,parent_comment_id: comment.id,parent_page: comment_replies.next_page), remote: true,data: {id: "next-page-#{comment.id}"} %>
      </div>
    <% end %>
  <% end %>
</div>
<% if is_parent_comment %>
<hr>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@task,Comment.new] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="row form-group align-items-center">
    <div class="col-sm-7">
      <%= f.text_area "content", class: "form-control",required: true %>
    </div>
    <div class="col-sm-3">
      <%= f.submit "Post",class: "btn btn-primary" %>
    </div>
  </div>
  <%= f.hidden_field "user_id",value: current_user.id unless current_user.nil? %>
  <%= f.hidden_field "task_id",value: @task.id %>
  <%= f.hidden_field "parent_comment_id",value: @parent_comment_id %>
<% end %>

app/views/comments/index.js.erb
<% if params[:parent_comment_id].present? %>
  $('[data-id="link-wrap-<%= params[:parent_comment_id] %>"]').append('<%= j render(@comments,recursive: true ) %>');
   <% if @comments.next_page %>
       $('[data-id="next-page-<%= params[:parent_comment_id] %>"]').attr('href','<%= task_comments_path(@task.id,parent_comment_id: params[:parent_comment_id],parent_page: @comments.next_page) %>');
  <% else %>
    $('[data-id="comment-more-<%= params[:parent_comment_id] %>"]').remove();
  <% end %>
<% else %>
  $('[data-id="link-wrap"]').append('<%= j render(@comments) %>');
  <% if @comments.next_page %>
       $('[data-id="next-page"]').attr('href','<%= task_comments_path(@task.id,page: @comments.next_page) %>');
  <% else %>
    $('[data-id="comment-more"]').remove();
  <% end %>
<% end %>

app/views/comments/new.js.erb
$("[data-id='comment-form'] [data-id='render-form']").html("");
$("[data-comment-id="+<%= @parent_comment_id %>+"]").find("[data-id='render-form']").append("<%= j render partial: 'comments/form'  %>")

app/views/layouts/_left_content.html.erb
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>Demo</h3>
        <strong>BS</strong>
    </div>
    
    <ul class="list-unstyled components">
        <li class="active">
            <%= link_to "My Projects", projects_path %>
            <%= link_to "My Tasks", tasks_path %>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome JS -->
    <script defer="" src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer="" src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="wrapper">
       <%= render partial: "layouts/left_content" if current_user %>
       
       <div id="content">
           <%= link_to('Logout', destroy_user_session_path, method: :delete,class: "float-right") %>        

         <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  
    <div class="field">
    <%= form.label :users %>
  <%= form.collection_select :user_ids, User.order(:email),:id,:email, {},{ :multiple => true, :size => 5 } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card bg-light">
  <div class="card-header">
    Projects
    <%= link_to 'New Project', new_project_path,class: "btn btn-primary float-right" %>

  </div>
    <div class="card-body">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
    
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Create Task', new_task_path(project_id: project.id) ,class: "btn btn-link" %>
                <%= link_to 'Show', project,class: "btn btn-link" %>
                <%= link_to 'Edit', edit_project_path(project),class: "btn btn-link" %>
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-link" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.collection_select :project_id, current_user.projects.order(:name),:id,:name,selected: params[:project_id], multiple: true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys %>
</div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card bg-light">
  <div class="card-header">
    Tasks
    <%= link_to 'New Task', new_task_path,class: "btn btn-primary float-right" %>

  </div>
    <div class="card-body">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
      <th>Project</th>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>User</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.project.name %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.user.email %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @task.project.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user.email %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

<hr/><h3><b>Comments</b></h3><hr/>
<div data-id="reply">
  <%= render partial: "comments/form" %>
</div>
<div class="container">
  <div data-id="link-wrap">
    <%= render(@comments) %>
  </div>
  <% if @comments.next_page %>
    <div data-id="comment-more">
      <%= link_to 'Load More', task_comments_path(@task.id,page: @comments.next_page), remote: true,data: {id: "next-page"} %>
    </div>
  <% end %>
</div>